// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/** Character sets by name. */
export declare const SETS: {
    ramp: string;
    ascii: string;
    blocks: string;
    binary: string;
};
export declare const REGIONS: number[];
/**
 * "8x12" -> [8, 12]; "10" -> [10, 10]. Cells are 2–32 pixels a side.
 * @param {string | undefined | null} text
 * @returns {[number, number]}
 */
export declare function parseCell(text: string | undefined | null): [number, number];
/**
 * The characters to choose from: a named set, or the characters given.
 * Defaults: `ramp` for brightness mode, `ascii` for shape mode.
 * @param {string} chars
 * @param {string} mode
 * @returns {string[]}
 */
export declare function resolveChars(chars: string, mode: string): string[];
/**
 * The atlas for these characters in this font at this cell size.
 * @param {string[]} chars
 * @param {string} family a CSS font-family list
 * @param {number} width cell width
 * @param {number} height cell height
 * @returns {{ chars: string[], width: number, height: number, alpha: Uint8ClampedArray, image: ImageData,
 *   brightness: Uint8Array, regions: Uint8Array, regionScale: number, features: ImageData, key: string }}
 */
export declare function glyphAtlas(chars: string[], family: string, width: number, height: number): {
    chars: string[];
    width: number;
    height: number;
    alpha: Uint8ClampedArray;
    image: ImageData;
    brightness: Uint8Array;
    regions: Uint8Array;
    regionScale: number;
    features: ImageData;
    key: string;
};
export declare function regionBounds(r: any, width: any, height: any): number[];
/**
 * Choose a character for every cell of `image`. Light is ink: a bright
 * cell gets an inky character (light on dark). With `invert` (a light
 * background), darkness is ink instead. Transparent pixels count as dark.
 * @param {ImageData} image
 * @param {ReturnType<typeof glyphAtlas>} atlas
 * @param {{ mode?: "brightness" | "shape", invert?: boolean }} [options]
 * @returns {{ columns: number, rows: number, indices: Uint16Array, colors: Uint8ClampedArray }}
 *   `colors`: each cell's average color (RGBA), weighted by alpha
 */
export declare function chooseGlyphs(image: ImageData, atlas: ReturnType<typeof glyphAtlas>, { mode, invert }?: {
    mode?: "brightness" | "shape";
    invert?: boolean;
}): {
    columns: number;
    rows: number;
    indices: Uint16Array;
    colors: Uint8ClampedArray;
};
/**
 * The chosen characters as text, one line per row (trailing spaces trimmed).
 * @param {ReturnType<typeof chooseGlyphs>} choice
 * @param {string[]} chars
 * @returns {string}
 */
export declare function glyphText({ columns, rows, indices }: ReturnType<typeof chooseGlyphs>, chars: string[]): string;
