// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * Fires "define" (with the effect's `name` in `detail`) when an effect is
 * registered, so a <pixel-canvas> waiting on it can redraw.
 */
export declare const effectRegistry: EventTarget;
export type EffectParams = Record<string, string> & {
    args: string[];
};
export type EffectContext = {
    time: number;
    frame: number;
    pointer?: {
        x: number;
        y: number;
        inside: boolean;
        down: boolean;
    } | null;
};
export type GpuEffect = {
    fragment: string;
    uniforms?: (params: EffectParams, size: {
        width: number;
        height: number;
    }, context: EffectContext) => Record<string, unknown>;
    supports?: (params: EffectParams) => boolean;
};
export type Effect = {
    name: string;
    params: string[];
    apply: (image: ImageData, params: EffectParams, context: EffectContext) => ImageData | void;
    gpu?: GpuEffect;
    pointer?: boolean;
};
/**
 * @typedef {Record<string, string> & { args: string[] }} EffectParams
 *   Parameter values as written (strings), by name. `args` holds
 *   positional values beyond the declared parameters.
 * @typedef {{ time: number, frame: number, pointer?: { x: number, y: number, inside: boolean, down: boolean } | null }} EffectContext
 *   When the effect is running: `time` is seconds on the <pixel-canvas>
 *   clock (which stops while it's paused), `frame` counts its redraws, and
 *   `pointer` is where the pointer is, in the image's pixels (0,0 at the
 *   top left; null before it's been over the canvas). Effects that change
 *   over time or follow the pointer use these; most ignore them.
 * @typedef {{
 *   fragment: string,
 *   uniforms?: (params: EffectParams, size: { width: number, height: number }, context: EffectContext) => Record<string, unknown>,
 *   supports?: (params: EffectParams) => boolean,
 * }} GpuEffect
 *   The same effect as a GLSL fragment shader, for <pixel-canvas gpu> (see
 *   gpu.mjs). `supports` says when it can't (some parameters need the CPU).
 * @typedef {{ name: string, params: string[], apply: (image: ImageData, params: EffectParams, context: EffectContext) => ImageData | void, gpu?: GpuEffect, pointer?: boolean }} Effect
 */
/**
 * Register an effect under `name`: usable as `name(…)` in an `effects`
 * attribute and as a `<pixel-name>` element (unless that tag is taken).
 * `params` lists the parameter names, in the order positional values fill
 * them. `apply` gets the ImageData and the parameter values (strings), and
 * returns an ImageData (or changes the one it got). A third argument,
 * `{ time, frame, pointer }`, is there for effects that change over time or
 * follow the pointer. `gpu` is the same effect in GLSL, for `<pixel-canvas
 * gpu>`; `pointer: true` redraws the canvas as the pointer moves.
 * @param {string} name
 * @param {(image: ImageData, params: EffectParams, context: EffectContext) => ImageData | void} apply
 * @param {{ params?: string[], element?: boolean, gpu?: GpuEffect, pointer?: boolean }} [options]
 * @returns {Effect}
 */
export declare function definePixelEffect(name: string, apply: (image: ImageData, params: EffectParams, context: EffectContext) => ImageData | void, { params, element, gpu, pointer }?: {
    params?: string[];
    element?: boolean;
    gpu?: GpuEffect;
    pointer?: boolean;
}): Effect;
/**
 * The registered effect called `name`, if any.
 * @param {string} name
 * @returns {Effect | undefined}
 */
export declare const getPixelEffect: (name: string) => Effect | undefined;
/**
 * Parse an `effects` attribute into calls, in order:
 * `"mosaic(4) palette(gameboy, ordered)"` ->
 * `[{ name: "mosaic", args: ["4"] }, { name: "palette", args: ["gameboy", "ordered"] }]`.
 * Parentheses are optional for an effect with no arguments (`outline`).
 * @param {string} text
 * @returns {{ name: string, args: string[] }[]}
 */
export declare function parseEffects(text: string): {
    name: string;
    args: string[];
}[];
/**
 * Turn a call's arguments into named parameters. An argument whose first
 * word is a parameter name is named (`contrast 1.3`); the rest fill the
 * unnamed parameters in order (`palette(gameboy, ordered)`).
 * @param {Effect} effect
 * @param {string[]} args
 * @returns {EffectParams}
 */
export declare function resolveParams(effect: Effect, args: string[]): EffectParams;
/**
 * Base class for effect elements. With a static `effect` (as
 * definePixelEffect makes), it applies that effect with its attributes as
 * the parameters; otherwise override `apply()`.
 */
export declare class PixelEffect extends HTMLElement {
    /** @type {Effect | undefined} */
    static effect: Effect | undefined;
    /**
     * The effect's parameters, read from this element's attributes.
     * @type {EffectParams}
     */
    get params(): EffectParams;
    /**
     * Transform the image (by default, with this element's effect).
     * @param {ImageData} image
     * @param {EffectContext} [context]
     * @returns {ImageData}
     */
    apply(image: ImageData, context?: EffectContext): ImageData;
    /**
     * This effect as a GPU pass (a fragment shader and its uniforms), or null
     * if it can only run on the CPU.
     * @param {{ width: number, height: number }} size
     * @param {EffectContext} context
     * @returns {{ fragment: string, uniforms: Record<string, unknown> } | null}
     */
    gpuPass(size: {
        width: number;
        height: number;
    }, context: EffectContext): {
        fragment: string;
        uniforms: Record<string, unknown>;
    } | null;
    /**
     * Whether the effect is switched off (the image passes through).
     * Mirrors the `disabled` attribute.
     * @type {boolean}
     */
    get disabled(): boolean;
    set disabled(value: boolean);
    /**
     * Ask the enclosing <pixel-canvas> to redraw, after a change it can't
     * see (attribute changes are seen already).
     */
    invalidate(): void;
}
/**
 * A parameter as a number, clamped, or `fallback` if it isn't one.
 * @param {string | undefined | null} value
 * @param {number} fallback
 * @param {{ min?: number, max?: number }} [range]
 * @returns {number}
 */
export declare function number(value: string | undefined | null, fallback: number, { min, max }?: {
    min?: number;
    max?: number;
}): number;
/**
 * @param {string | undefined | null} color
 * @returns {[number, number, number, number] | null} null if it isn't a color
 */
export declare function parseColor(color: string | undefined | null): [number, number, number, number] | null;
/**
 * A repeatable random-number generator: the same seed gives the same
 * sequence (mulberry32). For effects that should look random but not
 * flicker between redraws of the same frame.
 * @param {number} seed
 * @returns {() => number} numbers in [0, 1)
 */
export declare function random(seed: number): () => number;
/**
 * Perceived brightness of an RGB color, 0–255.
 * @param {number} r @param {number} g @param {number} b
 * @returns {number}
 */
export declare const luminance: (r: number, g: number, b: number) => number;
/**
 * An effect with these parameters as a GPU pass, or null if it has no GPU
 * version or this use of it needs the CPU.
 * @param {Effect} effect
 * @param {EffectParams} params
 * @param {{ width: number, height: number }} size
 * @param {EffectContext} context
 * @returns {{ fragment: string, uniforms: Record<string, unknown> } | null}
 */
export declare function gpuPass(effect: Effect, params: EffectParams, size: {
    width: number;
    height: number;
}, context: EffectContext): {
    fragment: string;
    uniforms: Record<string, unknown>;
} | null;
/**
 * The calls part of the way from one `effects` list to another, for
 * transitions: when both name the same effects in the same order, every
 * number that's in both (with the same unit) is interpolated, and anything
 * else takes the new value. When the effects differ, returns null (the
 * caller cross-fades instead).
 * @param {string} from
 * @param {string} to
 * @param {number} t 0 (from) to 1 (to)
 * @returns {{ name: string, args: string[] }[] | null}
 */
export declare function interpolateEffects(from: string, to: string, t: number): {
    name: string;
    args: string[];
}[] | null;
