// Generated by tsc from JSDoc (npm run manifest). Do not edit.
/**
 * Encode frames as an animated GIF.
 * @param {ImageData[]} frames all the same size
 * @param {{ delay?: number, loop?: number }} [options] `delay`: milliseconds
 *   per frame (GIF stores hundredths; default 100); `loop`: 0 repeats
 *   forever (the default), n repeats n more times, -1 plays once
 * @returns {Uint8Array}
 */
export declare function encodeGIF(frames: ImageData[], { delay, loop }?: {
    delay?: number;
    loop?: number;
}): Uint8Array;
