// Generated by tsc from JSDoc (npm run manifest). Do not edit.
export declare const PRELUDE = "#version 300 es\nprecision highp float;\nuniform sampler2D u_image;\nuniform vec2 u_resolution;\nuniform float u_time;\nuniform float u_frame;\nuniform vec3 u_pointer;\nin vec2 v_uv;\nout vec4 color;\n// This pixel's coordinates (0,0 at the top left), and the color at another.\nvec2 pixelAt() { return floor(v_uv * u_resolution); }\nvec4 sampleAt(vec2 p) { return texture(u_image, (clamp(p, vec2(0.0), u_resolution - 1.0) + 0.5) / u_resolution); }\n";
/**
 * A complete fragment shader from an effect's declarations and main().
 * @param {string} body
 * @returns {string}
 */
export declare const gpuShader: (body: string) => string;
/**
 * The pipeline for a WebGL2 context (made on first use).
 * @param {WebGL2RenderingContext} gl
 */
export declare function pipelineFor(gl: WebGL2RenderingContext): any;
/** A WebGL2 context shared by every <pixel-canvas> drawing an ordinary source. */
export declare function sharedContext(): any;
/** Whether this browser can run the GPU path at all. */
export declare function gpuAvailable(): boolean;
